// <auto-generated />
using System;
using BoardingKennelBookings.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardingKennelBookings.Migrations
{
    [DbContext(typeof(KennelContext))]
    [Migration("20260312151741_ModifyBookingTable")]
    partial class ModifyBookingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AMPickup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PMPickup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Dog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VacinationCertificateImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Kennel", b =>
                {
                    b.Property<int>("KennelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KennelID"));

                    b.Property<Guid?>("BookingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KennelNumber")
                        .HasColumnType("int");

                    b.HasKey("KennelID");

                    b.HasIndex("BookingID");

                    b.ToTable("Kennels");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Owner", b =>
                {
                    b.Property<Guid>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("BookingDog", b =>
                {
                    b.Property<Guid>("BookingsBookingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DogsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingsBookingID", "DogsID");

                    b.HasIndex("DogsID");

                    b.ToTable("BookingDog");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Booking", b =>
                {
                    b.HasOne("BoardingKennelBookings.Components.Models.Owner", "Owner")
                        .WithMany("Bookings")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Dog", b =>
                {
                    b.HasOne("BoardingKennelBookings.Components.Models.Owner", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Kennel", b =>
                {
                    b.HasOne("BoardingKennelBookings.Components.Models.Booking", null)
                        .WithMany("Kennels")
                        .HasForeignKey("BookingID");
                });

            modelBuilder.Entity("BookingDog", b =>
                {
                    b.HasOne("BoardingKennelBookings.Components.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsBookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardingKennelBookings.Components.Models.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogsID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Booking", b =>
                {
                    b.Navigation("Kennels");
                });

            modelBuilder.Entity("BoardingKennelBookings.Components.Models.Owner", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
